---
title: "Food Supply Datasets"
format:
  html:
    embed-resources: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DT)
```

### {.tabset}

#### GDP

```{r gdp-table, echo=FALSE, warning=FALSE}
gdp <- read.csv("../data/CleanedData/gdp.csv", fileEncoding = "UTF-8")
datatable(gdp[,-1], options = list(searchHighlight = TRUE, pageLength = 5))
```

#### Dietary Adequacy

```{r energy-table, echo=FALSE, warning=FALSE}
energy <- read.csv("../data/CleanedData/energyadequacy.csv", fileEncoding = "UTF-8")
datatable(energy[,-1], options = list(searchHighlight = TRUE, pageLength = 5))
```

#### Food Stability by Gender

```{r gender-table, echo=FALSE, warning=FALSE}
gender <- read.csv("../data/CleanedData/foodinsecuritybygender_cleaned.csv", fileEncoding = "UTF-8")
datatable(gender[,-1], options = list(searchHighlight = TRUE, pageLength = 5))
```

#### Obesity

```{r obesity-table, echo=FALSE, warning=FALSE}
obesity <- read.csv("../data/CleanedData/obesityadults.csv", fileEncoding = "UTF-8")
datatable(obesity[,-1], options = list(searchHighlight = TRUE, pageLength = 5))
```

#### Malnutrition

```{r malnour-table, echo=FALSE, warning=FALSE}
malnour <- read.csv("../data/CleanedData/undernourishment.csv", fileEncoding = "UTF-8")
datatable(malnour[,-1], options = list(searchHighlight = TRUE, pageLength = 5))
```

#### Political Stability

```{r politics-table, echo=FALSE, warning=FALSE}
politics <- read.csv("../data/CleanedData/politicalstability.csv", fileEncoding = "UTF-8")
datatable(politics[,-1], options = list(searchHighlight = TRUE, pageLength = 5))
```

#### Protein Supply

```{r protein-table, echo=FALSE, warning=FALSE}
protein <- read.csv("../data/CleanedData/proteinsupply.csv", fileEncoding = "UTF-8")
datatable(protein[,-1], options = list(searchHighlight = TRUE, pageLength = 5))
```


